# Ours
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "eth_unified_K=10" --train_datasets hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets eth --sample_num 10 --required_memory_MB 10000
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "hotel_unified_K=10" --train_datasets eth zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets hotel --sample_num 10 --required_memory_MB 10000
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara01_unified_K=10" --train_datasets eth hotel zara02 univ GC_train SDD_train WayMo_train --test_datasets zara01 --sample_num 10 --required_memory_MB 10000
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara02_unified_K=10" --train_datasets eth hotel zara01 univ GC_train SDD_train WayMo_train --test_datasets zara02 --sample_num 10 --required_memory_MB 10000
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "univ_unified_K=10" --train_datasets eth hotel zara01 zara02 GC_train SDD_train WayMo_train --test_datasets univ --sample_num 10 --required_memory_MB 10000
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_SDD_WayMo_unified_K=10" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --required_memory_MB 10000

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10 --batch_size 10 --reload_checkpoint ./logs/train/eth_single_K=10/best.pth
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/hotel_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/zara01_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/zara02_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/univ_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/GC_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/SDD_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/WayMo_single_K=10/best.pth"

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "eth_unified_K=10" --train_datasets hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets eth --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/eth_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "hotel_unified_K=10" --train_datasets eth zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets hotel --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/hotel_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "zara01_unified_K=10" --train_datasets eth hotel zara02 univ GC_train SDD_train WayMo_train --test_datasets zara01 --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/zara01_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "zara02_unified_K=10" --train_datasets eth hotel zara01 univ GC_train SDD_train WayMo_train --test_datasets zara02 --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/zara02_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "univ_unified_K=10" --train_datasets eth hotel zara01 zara02 GC_train SDD_train WayMo_train --test_datasets univ --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/univ_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python test.py --exp_name "GC_SDD_WayMo_unified_K=10" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --batch_size 10 --reload_checkpoint "./logs/train/GC_SDD_WayMo_unified_K=10/best.pth"

conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_sfm.py --minimize_gpu --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10

conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_social_stgcnn.py --minimize_gpu --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10

conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --minimize_gpu --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10

conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_spdiff.py --exp_name "GC_SDD_WayMo_unified_K=10" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10

conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_mid.py --minimize_gpu --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10

conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10
conda activate ./venv && export PYTHONPATH=. && python ./baselines/train_trace.py --minimize_gpu --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10

# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "eth_unified_K=10_wo_nan_embedding" --train_datasets hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets eth --sample_num 10 --required_memory_MB 5000 --no-use_nan_embedding
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "hotel_unified_K=10_wo_nan_embedding" --train_datasets eth zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets hotel --sample_num 10 --required_memory_MB 5000 --no-use_nan_embedding
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara01_unified_K=10_wo_nan_embedding" --train_datasets eth hotel zara02 univ GC_train SDD_train WayMo_train --test_datasets zara01 --sample_num 10 --required_memory_MB 5000 --no-use_nan_embedding
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara02_unified_K=10_wo_nan_embedding" --train_datasets eth hotel zara01 univ GC_train SDD_train WayMo_train --test_datasets zara02 --sample_num 10 --required_memory_MB 5000 --no-use_nan_embedding
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "univ_unified_K=10_wo_nan_embedding" --train_datasets eth hotel zara01 zara02 GC_train SDD_train WayMo_train --test_datasets univ --sample_num 10 --required_memory_MB 5000 --no-use_nan_embedding

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "eth_single_K=10" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10 --reload_checkpoint ./logs/train/eth_single_K=10/best.pth
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "hotel_single_K=10" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10 --reload_checkpoint "./logs/train/hotel_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "zara01_single_K=10" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10 --reload_checkpoint "./logs/train/zara01_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "zara02_single_K=10" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10 --reload_checkpoint "./logs/train/zara02_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "univ_single_K=10" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10 --reload_checkpoint "./logs/train/univ_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "GC_single_K=10" --train_datasets GC_train --test_datasets GC_test --sample_num 10 --reload_checkpoint "./logs/train/GC_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "SDD_single_K=10" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10 --reload_checkpoint "./logs/train/SDD_single_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "WayMo_single_K=10" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10 --reload_checkpoint "./logs/train/WayMo_single_K=10/best.pth"

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "eth_unified_K=10" --train_datasets hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets eth --sample_num 10 --reload_checkpoint "./logs/train/eth_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "hotel_unified_K=10" --train_datasets eth zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets hotel --sample_num 10 --reload_checkpoint "./logs/train/hotel_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "zara01_unified_K=10" --train_datasets eth hotel zara02 univ GC_train SDD_train WayMo_train --test_datasets zara01 --sample_num 10 --reload_checkpoint "./logs/train/zara01_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "zara02_unified_K=10" --train_datasets eth hotel zara01 univ GC_train SDD_train WayMo_train --test_datasets zara02 --sample_num 10 --reload_checkpoint "./logs/train/zara02_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "univ_unified_K=10" --train_datasets eth hotel zara01 zara02 GC_train SDD_train WayMo_train --test_datasets univ --sample_num 10 --reload_checkpoint "./logs/train/univ_unified_K=10/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "GC_SDD_WayMo_unified_K=10" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --reload_checkpoint "./logs/train/GC_SDD_WayMo_unified_K=10/best.pth"

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_SDD_WayMo_unified_K=10_wo_nan_embedding" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --required_memory_MB 10000 --no-use_nan_embedding
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_SDD_WayMo_unified_K=10_wo_spatial_anchor" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --required_memory_MB 10000 --no-use_spatial_anchor
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_SDD_WayMo_unified_K=10_wo_latent_query" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --required_memory_MB 10000 --no-use_latent_query --test_per_epoch 100 --patience 2
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_SDD_WayMo_unified_K=10_wo_map" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --required_memory_MB 10000 --p_drop_map 1.0
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_SDD_WayMo_unified_K=10_wo_frequency_encoding" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --required_memory_MB 10000 --no-use_frequency_encoding
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC_SDD_WayMo_unified_K=10_wo_relative_features" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --required_memory_MB 10000 --no-use_relative_features



conda activate ./venv && python test.py --exp_name "eth_single_K=10_guidance" --train_datasets hotel zara01 zara02 univ --test_datasets eth --sample_num 10 --reload_checkpoint ./logs/train/eth_single_K=10/best.pth --cg_sfm_des 0.0020766158672711195 --cg_sfm_obs 0.043365303212513494 --cg_sfm_soc 0.09981135552036823
conda activate ./venv && python test.py --exp_name "hotel_single_K=10_guidance" --train_datasets eth zara01 zara02 univ --test_datasets hotel --sample_num 10 --reload_checkpoint "./logs/train/hotel_single_K=10/best.pth" --cg_sfm_des 8.03827479660418e-05 --cg_sfm_obs 0.027239694981206666 --cg_sfm_soc 0.09179955411863881
conda activate ./venv && python test.py --exp_name "zara01_single_K=10_guidance" --train_datasets eth hotel zara02 univ --test_datasets zara01 --sample_num 10 --reload_checkpoint "./logs/train/zara01_single_K=10/best.pth" --cg_sfm_des 5.7047953280044486e-05 --cg_sfm_obs 0.0065642419573719865 --cg_sfm_soc 0.09349818470071049
conda activate ./venv && python test.py --exp_name "zara02_single_K=10_guidance" --train_datasets eth hotel zara01 univ --test_datasets zara02 --sample_num 10 --reload_checkpoint "./logs/train/zara02_single_K=10/best.pth" --cg_sfm_des 0.0050211606341352775 --cg_sfm_obs 0.04534391058066792 --cg_sfm_soc 0.09935370673947709
conda activate ./venv && python test.py --exp_name "univ_single_K=10_guidance" --train_datasets eth hotel zara01 zara02 --test_datasets univ --sample_num 10 --reload_checkpoint "./logs/train/univ_single_K=10/best.pth" --cg_sfm_des 0.0013016742245967098 --cg_sfm_obs 0.004111642813928902 --cg_sfm_soc 0.09940760321404994
conda activate ./venv && python test.py --exp_name "GC_single_K=10_guidance" --train_datasets GC_train --test_datasets GC_test --sample_num 10 --reload_checkpoint "./logs/train/GC_single_K=10/best.pth" --cg_sfm_des 9.466893231993589e-05 --cg_sfm_obs 0.007702638446205876 --cg_sfm_soc 0.08992087981320815
conda activate ./venv && python test.py --exp_name "SDD_single_K=10_guidance" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10 --reload_checkpoint "./logs/train/SDD_single_K=10/best.pth" --cg_sfm_des 0.004374872244693018 --cg_sfm_obs 0.03258567764556952 --cg_sfm_soc 0.09549005629577936
conda activate ./venv && python test.py --exp_name "WayMo_single_K=10_guidance" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10 --reload_checkpoint "./logs/train/WayMo_single_K=10/best.pth" --cg_sfm_des 0.0005656649473232803 --cg_sfm_obs 0.045846185883210155 --cg_sfm_soc 0.0934384114194991
conda activate ./venv && python test.py --exp_name "eth_unified_K=10_guidance" --train_datasets hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets eth --sample_num 10 --reload_checkpoint "./logs/train/eth_unified_K=10/best.pth" --cg_sfm_des 0.0013110753532877717 --cg_sfm_obs 0.01700626444555118 --cg_sfm_soc 0.09938048968218256
conda activate ./venv && python test.py --exp_name "hotel_unified_K=10_guidance" --train_datasets eth zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets hotel --sample_num 10 --reload_checkpoint "./logs/train/hotel_unified_K=10/best.pth" --cg_sfm_des 0.007048672598533298 --cg_sfm_obs 0.03340290423813516 --cg_sfm_soc 0.09561787903259436
conda activate ./venv && python test.py --exp_name "zara01_unified_K=10_guidance" --train_datasets eth hotel zara02 univ GC_train SDD_train WayMo_train --test_datasets zara01 --sample_num 10 --reload_checkpoint "./logs/train/zara01_unified_K=10/best.pth" --cg_sfm_des 0.0012549783841595509 --cg_sfm_obs 0.027051701278952674 --cg_sfm_soc 0.0960227484376092
conda activate ./venv && python test.py --exp_name "zara02_unified_K=10_guidance" --train_datasets eth hotel zara01 univ GC_train SDD_train WayMo_train --test_datasets zara02 --sample_num 10 --reload_checkpoint "./logs/train/zara02_unified_K=10/best.pth" --cg_sfm_des 0.00914369076650318 --cg_sfm_obs 0.021875452717823426 --cg_sfm_soc 0.09579248283484947
conda activate ./venv && python test.py --exp_name "univ_unified_K=10_guidance" --train_datasets eth hotel zara01 zara02 GC_train SDD_train WayMo_train --test_datasets univ --sample_num 10 --reload_checkpoint "./logs/train/univ_unified_K=10/best.pth" --cg_sfm_des 0.00057068888516058 --cg_sfm_obs 0.010961701895698785 --cg_sfm_soc 0.09997371390784329
conda activate ./venv && python test.py --exp_name "GC_SDD_WayMo_unified_K=10_guidance" --train_datasets eth hotel zara01 zara02 univ GC_train SDD_train WayMo_train --test_datasets GC_test SDD_test WayMo_test --sample_num 10 --reload_checkpoint "./logs/train/GC_SDD_WayMo_unified_K=10/best.pth" --cg_sfm_des 0.0023307844591004614 --cg_sfm_obs 0.019613331361756303 --cg_sfm_soc 0.09324556610324777


# 华为要的补充实验
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "eth" --train_datasets eth --test_datasets eth hotel zara01 zara02 univ GC_test SDD_test WayMo_test --sample_num 10
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "hotel" --train_datasets hotel --test_datasets eth hotel zara01 zara02 univ GC_test SDD_test WayMo_test --sample_num 10
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara01" --train_datasets zara01 --test_datasets eth hotel zara01 zara02 univ GC_test SDD_test WayMo_test --sample_num 10
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "zara02" --train_datasets zara02 --test_datasets eth hotel zara01 zara02 univ GC_test SDD_test WayMo_test --sample_num 10
# conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "univ" --train_datasets univ --test_datasets eth hotel zara01 zara02 univ GC_test SDD_test WayMo_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "ETH" --train_datasets ETH_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "UCY" --train_datasets UCY_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "GC" --train_datasets GC_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "SDD" --train_datasets SDD_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "WayMo" --train_datasets WayMo_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "All" --train_datasets ETH_train UCY_train GC_train SDD_train WayMo_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "All-faster" --train_datasets ETH_train UCY_train GC_train SDD_train WayMo_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10 --patience 5 --test_per_epoch 40

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python train.py --exp_name "All_wo_Latent_Query" --train_datasets ETH_train UCY_train GC_train SDD_train WayMo_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10 --no-use_latent_query --no-cache_latent_query

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "All" --train_datasets ETH_train UCY_train GC_train SDD_train WayMo_train --test_datasets ETH_test UCY_test GC_test SDD_test WayMo_test --sample_num 10 --reload_checkpoint "./logs/train/All/best.pth"

conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "All@ETH" --train_datasets ETH_train --test_datasets ETH_test --sample_num 10 --reload_checkpoint "./logs/train/All/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "All@UCY" --train_datasets UCY_train --test_datasets UCY_test --sample_num 10 --reload_checkpoint "./logs/train/All/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "All@GC" --train_datasets GC_train --test_datasets GC_test --sample_num 10 --reload_checkpoint "./logs/train/All/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "All@SDD" --train_datasets SDD_train --test_datasets SDD_test --sample_num 10 --reload_checkpoint "./logs/train/All/best.pth"
conda activate ./venv && export CUDA_VISIBLE_DEVICES=0,1,2,3 && python calibrate_optune.py --exp_name "All@WayMo" --train_datasets WayMo_train --test_datasets WayMo_test --sample_num 10 --reload_checkpoint "./logs/train/All/best.pth"